### PR TITLE
Add option for using society money

### LINKED ISSUE #86: Addition: Remove $ from BossMenu Factions
Just looking for an addition to be able to remove money from a factions bank account. 

Example:

If I have several jobs in the server utilizing the bennys for upgrades or cosmetics, the cost would come out of that jobs account.

### LINKED ISSUE #130: [BUG] Society not being used?
**Describe the bug**
We used to set cash/bank/society to cover costs of the car changes, then you would bill the customer, since the last big update only cash/bank works?

**To Reproduce**
1. Set job
2. Repair a car
3. comes out of your bank not the business

**Expected behavior**
Setting config.moneytype to society should be an option and it takes it out of the management fund.

**Questions (please complete the following information):**
 - When you last updated: Current
 - Are you using custom resource? which ones? N/A
 - Have you renamed `qb-` to something custom? No

**Additional context**
Might be an oversight or maybe society shouldn't be used? instead management or maybe evne the job name? e.g. mechnic?

### LINKED ISSUE #135: [SUPPORT] Society use
Hello.

How i can do that if mechanic tuning someone's car it takes money from mechanic society not from player bank?

### PR DESCRIPTION
**Pull request by D4isDAVID**
**Describe Pull request**
This adds:
1. An option for job societies to pay for their employees when in a customs location that is restricted to that same job
2. An option for certain job societies to always pay for their employees regardless of the location

If the society does not have enough money then the employee gets charged instead.

Resolves #86
Fixes #130
Resolves #135

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? **yes**
- Does your code fit the style guidelines? **yes**
- Does your PR fit the contribution guidelines? **yes**

### CODE REVIEW

**Comment by Griefa** [comment]
Getting this error

https://i.imgur.com/YoItM82.png

**Comment by D4isDAVID** [comment]
> Getting this error
> 
> https://i.imgur.com/YoItM82.png

Looks to me like you modified the script in some way? My file changes don't include a `)` in line 84.

**Comment by Griefa** [comment]
> 

Yeah, I seemed to fix it. 

However, I'm getting an issue where the society funds aren't being removed. 

**Before upgrading vehicles**
https://i.imgur.com/8LSGb5x.png

**After purchasing ALL performance upgrades**
https://i.imgur.com/JudhqrF.png

I have updated qb-management, I have also made sure to set "Config.PayWithSocietyWhenJobRestricted to true. 

Am I missing anything?

**Comment by D4isDAVID** [comment]
@Griefa infinite money problem should be solved now.

**Comment by Griefa** [comment]
@D4isDAVID everything works perfectly! It's ready for merge whenever Stan is happy with it

**Pull request merged**
