### PR TITLE
Code Cleanup + Added Percentages for Performance Upgrades

### PR DESCRIPTION
**Pull request by Demo4889**
This has been tested by purchasing every mod in the customs shop and making sure the bank removes the correct amount of money per performance and other upgrades.

I also cleaned up some of the coding, deleting the extra spacing in the files.

### CODE REVIEW

**Comment by xenfovn** [comment]
nil carPrice

**Comment by Demo4889** [comment]
What car were you trying to modify? Make sure the car is in the core shared.lua file

**Comment by jnccloud** [comment]
> What car were you trying to modify? Make sure the car is in the core shared.lua file

What I'm guessing happened here is that this won't work properly because of NPC vehicles. Can you introduce a nil check to resort to a default value if the car doesn't exist in shared.lua? That would still allow customizations of local vehicles that are in a server but aren't purchasable or listed in shared.lua.

**Comment by Demo4889** [comment]
I'll work on it at some point. This is already 2 months old so... im sure the locales still need to be done as well. So ill do them all at once with some testing and update my files.

**Comment by ItsANoBrainer** [comment]
Conflicts exist. Someone else updated it here:
https://github.com/qbcore-framework/qb-customs/pull/77

**Comment by Rav3n95** [comment]
> Conflicts exist. Someone else updated it here: #77

Since its more than a month old, its outdated, also percentage only apply to performance updates. On mine its apply for everything exept repair. In my resource its also just a option.

**Pull request closed without merging**
