### PR TITLE
Options to add multiple benny's location.

### PR DESCRIPTION
**Pull request by pushkart2**
You can add multiple locations. Just add them in bennyGarages

### CODE REVIEW

**Comment by BerkieBb** [comment]
Can you make this a config option instead of it being in the client file? Might be better understandable for people newer to coding and it's a more understandable place to put it

**Comment by pushkart2** [comment]
> 
> 
> Can you make this a config option instead of it being in the client file? Might be better understandable for people newer to coding and it's a more understandable place to put it

done.. also added job check if people want it..

**Comment by BerkieBb** [comment]
Perfect, I'll test this later and I'll get back to you if there are any problems and otherwise I'll merge it

**Comment by BerkieBb** [comment]
Line 844:
Change 
`isAuthorized((QBCore.Functions.GetPlayerData().job.name), k))`

To 

`isAuthorized(QBCore.Functions.GetPlayerData().job.name), k)`

**Comment by BerkieBb** [comment]
Line 844:
Change 
`isAuthorized((QBCore.Functions.GetPlayerData().job.name), k))`

To 

`isAuthorized(QBCore.Functions.GetPlayerData().job.name, k)`

**Comment by morwic** [comment]
I check this with 15 shops all set to different jobs and it works perfectly.

**Comment by pushkart2** [comment]
> 
> 
> Line 844:
> Change
> `isAuthorized((QBCore.Functions.GetPlayerData().job.name), k))`
> 
> To
> 
> `isAuthorized(QBCore.Functions.GetPlayerData().job.name, k)`

done

**Comment by BerkieBb** [comment]
Can you instead of the Config.Job option make a useJob option inside every garage so you can set it per garage?

**Comment by pushkart2** [comment]
> 
> 
> Can you instead of the Config.Job option make a useJob option inside every garage so you can set it per garage?

done

**Comment by vanillla1** [comment]
Can in this update
When the mechanic online
The citizen can not repair or modify his vehicle?
Ease of adding sites bennys ?

**Pull request merged**
