### PR TITLE
Fix cost of upgrades to come from bank account

### PR DESCRIPTION
**Pull request by OfficiallyM**
Customs should probably utilise the core money system rather than qb-bossmenu?

### CODE REVIEW

**Comment by GhzGarage** [comment]
Why would mechanics have to pay out of their personal bank accounts

**Comment by tommybtels** [comment]
> Why would mechanics have to pay out of their personal bank accounts

Not the issue, issue is players cannot use their own money to buy upgrades for their owned vehicles @GhzGarage

**Comment by OfficiallyM** [comment]
> Why would mechanics have to pay out of their personal bank accounts

The ideal solution would be to change the account the money comes from depending on the job of the player.
With this not done however, the current setup means nobody but a mechanic can upgrade or repair their vehicle.

This is not ideal for any server, and i'd rather have 99% of players being able to upgrade their car, than the 1% who play the mechanic job.

**Comment by OfficiallyM** [comment]
Fixed so player money comes from bank account, but mechanics have their money withdrawn from the boss acccount

**Pull request merged**
