### PR TITLE
Performance increase change to drawtext

### PR DESCRIPTION
**Pull request by Kmack710**
Using new qb drawtext to drop resmon by 0.04

### CODE REVIEW

**Comment by mk3ext** [comment]
I think you may of commited the wrong file?

**Comment by Kmack710** [comment]
> I think you may of commited the wrong file?

No? There is 2 parts. Vector4 was no longer needed as heading was pointless and only spun your car around to a specific heading that most the time wasnt the way you were looking

**Comment by Tomboru** [comment]
But you commited a config.lua.

That has nothing to do with drawtext. >.>

**Comment by Kmack710** [comment]
> But you commited a config.lua.
> 
> That has nothing to do with drawtext. >.>

There is 2 PRs lol look at the full thing first I just did this PR online. So its 1 per file. QBCore already knows and this is just waiting for the dev branch to get merged with main before it gets pushed.

**Comment by ItsANoBrainer** [comment]
Thanks for the request.

This idea will be added in the larger rework here: https://github.com/qbcore-framework/qb-customs/pull/71

**Pull request closed without merging**
